#include "kernel/input/types.h"

const char *
get_key_name(keyboard_input_key_e key)
{
   switch (key)
   {
   case KEY_UNKNOWN:
      return "KEY_UNKNOWN";
   case KEY_ESC:
      return "KEY_ESC";
   case KEY_1:
      return "KEY_1";
   case KEY_2:
      return "KEY_2";
   case KEY_3:
      return "KEY_3";
   case KEY_4:
      return "KEY_4";
   case KEY_5:
      return "KEY_5";
   case KEY_6:
      return "KEY_6";
   case KEY_7:
      return "KEY_7";
   case KEY_8:
      return "KEY_8";
   case KEY_9:
      return "KEY_9";
   case KEY_0:
      return "KEY_0";
   case KEY_LAYOUT_01:
      return "KEY_LAYOUT_01";
   case KEY_LAYOUT_02:
      return "KEY_LAYOUT_02";
   case KEY_DEL:
      return "KEY_DEL";
   case KEY_TAB:
      return "KEY_TAB";
   case KEY_Q:
      return "KEY_Q";
   case KEY_W:
      return "KEY_W";
   case KEY_E:
      return "KEY_E";
   case KEY_R:
      return "KEY_R";
   case KEY_T:
      return "KEY_T";
   case KEY_Y:
      return "KEY_Y";
   case KEY_U:
      return "KEY_U";
   case KEY_I:
      return "KEY_I";
   case KEY_O:
      return "KEY_O";
   case KEY_P:
      return "KEY_P";
   case KEY_LAYOUT_03:
      return "KEY_LAYOUT_03";
   case KEY_LAYOUT_04:
      return "KEY_LAYOUT_04";
   case KEY_ENTER:
      return "KEY_ENTER";
   case KEY_L_CTRL:
      return "KEY_L_CTRL";
   case KEY_A:
      return "KEY_A";
   case KEY_S:
      return "KEY_S";
   case KEY_D:
      return "KEY_D";
   case KEY_F:
      return "KEY_F";
   case KEY_G:
      return "KEY_G";
   case KEY_H:
      return "KEY_H";
   case KEY_J:
      return "KEY_J";
   case KEY_K:
      return "KEY_K";
   case KEY_L:
      return "KEY_L";
   case KEY_LAYOUT_05:
      return "KEY_LAYOUT_05";
   case KEY_LAYOUT_06:
      return "KEY_LAYOUT_06";
   case KEY_LAYOUT_07:
      return "KEY_LAYOUT_07";
   case KEY_L_SHFT:
      return "KEY_L_SHFT";
   case KEY_BACKSLASH:
      return "KEY_BACKSLASH";
   case KEY_Z:
      return "KEY_Z";
   case KEY_X:
      return "KEY_X";
   case KEY_C:
      return "KEY_C";
   case KEY_V:
      return "KEY_V";
   case KEY_B:
      return "KEY_B";
   case KEY_N:
      return "KEY_N";
   case KEY_M:
      return "KEY_M";
   case KEY_COMMA:
      return "KEY_COMMA";
   case KEY_DOT:
      return "KEY_DOT";
   case KEY_LAYOUT_08:
      return "KEY_LAYOUT_08";
   case KEY_R_SHFT:
      return "KEY_R_SHFT";
   case KEY_KP_STAR:
      return "KEY_KP_STAR";
   case KEY_L_ALT:
      return "KEY_L_ALT";
   case KEY_SPACE:
      return "KEY_SPACE";
   case KEY_CAPS:
      return "KEY_CAPS";
   case KEY_F1:
      return "KEY_F1";
   case KEY_F2:
      return "KEY_F2";
   case KEY_F3:
      return "KEY_F3";
   case KEY_F4:
      return "KEY_F4";
   case KEY_F5:
      return "KEY_F5";
   case KEY_F6:
      return "KEY_F6";
   case KEY_F7:
      return "KEY_F7";
   case KEY_F8:
      return "KEY_F8";
   case KEY_F9:
      return "KEY_F9";
   case KEY_F10:
      return "KEY_F10";
   case KEY_NUMLOCK:
      return "KEY_NUMLOCK";
   case KEY_SCROLL_LOCK:
      return "KEY_SCROLL_LOCK";
   case KEY_KP_7:
      return "KEY_KP_7";
   case KEY_KP_8:
      return "KEY_KP_8";
   case KEY_KP_9:
      return "KEY_KP_9";
   case KEY_KP_4:
      return "KEY_KP_4";
   case KEY_KP_5:
      return "KEY_KP_5";
   case KEY_KP_6:
      return "KEY_KP_6";
   case KEY_KP_1:
      return "KEY_KP_1";
   case KEY_KP_2:
      return "KEY_KP_2";
   case KEY_KP_3:
      return "KEY_KP_3";
   case KEY_KP_0:
      return "KEY_KP_0";
   case KEY_KP_DOT:
      return "KEY_KP_DOT";
   case KEY_F11:
      return "KEY_F11";
   case KEY_F12:
      return "KEY_F12";
   case KEY_PREV_TRACK:
      return "KEY_PREV_TRACK";
   case KEY_NEXT_TRACK:
      return "KEY_NEXT_TRACK";
   case KEY_KP_ENTER:
      return "KEY_KP_ENTER";
   case KEY_R_CTRL:
      return "KEY_R_CTRL";
   case KEY_MUTE:
      return "KEY_MUTE";
   case KEY_CALCULATOR:
      return "KEY_CALCULATOR";
   case KEY_PLAY:
      return "KEY_PLAY";
   case KEY_STOP:
      return "KEY_STOP";
   case KEY_VOL_DOWN:
      return "KEY_VOL_DOWN";
   case KEY_VOL_UP:
      return "KEY_VOL_UP";
   case KEY_WWW_HOME:
      return "KEY_WWW_HOME";
   case KEY_KP_SLASH:
      return "KEY_KP_SLASH";
   case KEY_ALT_GR:
      return "KEY_ALT_GR";
   case KEY_HOME:
      return "KEY_HOME";
   case KEY_ARROW_UP:
      return "KEY_ARROW_UP";
   case KEY_PAGE_UP:
      return "KEY_PAGE_UP";
   case KEY_ARROW_LEFT:
      return "KEY_ARROW_LEFT";
   case KEY_ARROW_RIGHT:
      return "KEY_ARROW_RIGHT";
   case KEY_END:
      return "KEY_END";
   case KEY_ARROW_DOWN:
      return "KEY_ARROW_DOWN";
   case KEY_PAGE_DOWN:
      return "KEY_PAGE_DOWN";
   case KEY_INSERT:
      return "KEY_INSERT";
   case KEY_SUPR:
      return "KEY_SUPR";
   case KEY_LEFT_GUI:
      return "KEY_LEFT_GUI";
   case KEY_RIGHT_GUI:
      return "KEY_RIGHT_GUI";
   case KEY_APPS:
      return "KEY_APPS";
   case KEY_POWER:
      return "KEY_POWER";
   case KEY_SLEEP:
      return "KEY_SLEEP";
   case KEY_WAKE:
      return "KEY_WAKE";
   case KEY_WWW_SEARCH:
      return "KEY_WWW_SEARCH";
   case KEY_WWW_FAVS:
      return "KEY_WWW_FAVS";
   case KEY_WWW_REFRESH:
      return "KEY_WWW_REFRESH";
   case KEY_WWW_STOP:
      return "KEY_WWW_STOP";
   case KET_WWW_FORWARD:
      return "KEY_WWW_FORWARD";
   case KEY_WWW_BACK:
      return "KEY_WWW_BACK";
   case KEY_MY_COMP:
      return "KEY_MY_COMP";

   case KEY_EMAIL:
      return "KEY_EMAIL";
   case KEY_MEDIA_SELECT:
      return "KEY_MEDIA_SELECT";
   }
   return "UNKNOWN_KEY";
}
